import { type NextPage } from "next";
import Head from "next/head";
import { Room } from "~/components/room";
import {
  ApplicationSettingsProvider,
  type ApplicationSettings,
} from "~/providers";
import { getSettingsConstants } from "~/server/api/config";

interface RoomPageProps {
  settings: ApplicationSettings;
}

const RoomPage: NextPage<RoomPageProps> = ({ settings }) => {
  return (
    <>
      <Head>
        <title>Chat Room</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ApplicationSettingsProvider defaultStateOverride={settings}>
        <Room />
      </ApplicationSettingsProvider>
    </>
  );
};

RoomPage.getInitialProps = () => {
  const settings = getSettingsConstants();
  return { settings: settings };
};

export default RoomPage;
