import { type NextPage } from "next";
import Head from "next/head";
import dynamic, { type DynamicOptions } from "next/dynamic";
import {
  ApplicationSettingsProvider,
  type ApplicationSettings,
  _applicationSettings,
} from "~/providers";
import { getSettingsConstants } from "~/server/api/config";

const DynamicRoom = dynamic(
  import("~/components/room/room.tsx") as DynamicOptions,
  {
    ssr: false,
  }
);

interface RoomPageProps {
  settings: Partial<ApplicationSettings>;
}

const RoomPage: NextPage<RoomPageProps> = ({ settings }) => {
  console.log("settings");

  const mergedSettings: ApplicationSettings = {
    ...settings,
    ..._applicationSettings,
  };

  return (
    <>
      <Head>
        <title>Chat Room</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ApplicationSettingsProvider defaultStateOverride={mergedSettings}>
        <DynamicRoom />
      </ApplicationSettingsProvider>
    </>
  );
};

RoomPage.getInitialProps = () => {
  const settings = getSettingsConstants();
  return { settings: { ...settings } };
};

export default RoomPage;
