import { type NextPage } from "next";
import Head from "next/head";
import { UIButtonLink, UILink } from "~/components/ui";
import { Axlotl } from "~/components/assets/axlotl";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Axlglotl - A WebRTC Chat App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-sky-950 to-slate-900">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-sky-50 sm:text-[5rem]">
            Axl<span className="text-sky-400">glot</span>l
          </h1>

          <Axlotl />

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <UIButtonLink href="#" title="Create a Room">
              <h3 className="text-2xl font-bold">Create a Room</h3>
            </UIButtonLink>
            <UIButtonLink href="#" title="Join a Room">
              <h3 className="text-2xl font-bold">Join a Room</h3>
            </UIButtonLink>
          </div>
          <p className="text-1xl flex flex-col text-center text-sky-50">
            Built with: Trystero, ChatGPT, NextJS, tRPC, and Tailwind
            <UILink
              title={"Link to Github Repo"}
              href="https://github.com/JacksonCleary/axlglotl"
              external={true}
              center={true}
            >
              <span>Link to Repo</span>
            </UILink>
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
